### ISSUE TITLE
single quote character in medium post code listing not the same as `'`

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/d3_in_action_2#13]
![screen shot 2017-05-23 at 3 44 02 pm](https://cloud.githubusercontent.com/assets/2119400/26379578/bf6a1e52-3fce-11e7-964c-4b3911fd5b09.png)

https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71

**Comment by micahstubbs** [comment]
when I copy and paste the code from the medium post, it doesn't compile 😱

**Comment by emeeks** [comment]
Is it because medium is helpfully making the single quotes pretty or is it
something else? I can't tell from your screenshot.

(thanks for checking on this btw)

**Comment by micahstubbs** [comment]
@emeeks pretty quotes are the issue - seem to be entirely different characters 😂   hard to tell if medium transformed them from the original text.
