### ISSUE TITLE
top level index.html uses several incorrect file links

### ISSUE THREAD

**Issue by denisfitz57** [emeeks/d3_in_action_2#18]
First example is:

<li><a href="chapter3/3_2.html">3_2.html</a></li>

which should be:

<li><a href="chapter3/3_02.html">3_2.html</a></li>

This appears to be a general problem where there is a single digit after the underscore

**Comment by emeeks** [comment]
Thanks for noting this, I'll correct these.

**Comment by 8gentile** [comment]
3_02.html*

**Comment by emeeks** [comment]
Fixed it.
