### ISSUE TITLE
Typo on page 32

### ISSUE THREAD

**Issue by Selbosh** [emeeks/d3_in_action_2#19]
The code listing above Figure 1.28 begins
```javascript
smallerNumbers = someNumbers.filter(
  function(el) {return d <= 40});
```
The second line should say
```javascript
  function(el) {return el <= 40});
```

Figure 1.28 shows the correct code.

**Comment by emeeks** [comment]
Thanks for this @Selbosh and for all the other bits you've posted. They'll be added to the errata topic on the Manning forum for my book and will be corrected in a later printing. I really appreciate your taking the time to write these up--as much as I wish I hadn't made the original error, I'd rather it get corrected for future folks.

**Comment by emeeks** [comment]
https://forums.manning.com/posts/list/42082.page

**Comment by Selbosh** [comment]
You are welcome!
