### ISSUE TITLE
Error on page 87 of second edition

### ISSUE THREAD

**Issue by Selbosh** [emeeks/d3_in_action_2#20]
The code underneath Figure 3.7 has been changed to ES6 arrow notation without consideration for what it is supposed to demonstrate.

```javascript
d3.select('circle').each((d, i) => {
    console.log(d); console.log(i); console.log(this);
})
```
The paragraph immediately after this code listing says: "The last thing echoed to the console, `this`, is the `<circle>` DOM element itself." This may have been the case in the first edition when it was an anonymous `function()` declaration, but using arrow notation, `this` is undefined.

Either the code needs to be reverted or the text needs to be corrected.

**Comment by emeeks** [comment]
Ah, arrow functions are so good until they aren't.
